---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-muehlbachler-mail-services-infrastructure/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-muehlbachler-mail-services-infrastructure/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-muehlbachler-mail-services-infrastructure/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT ;
            github-muehlbachler-mail-services-infrastructure/data/aws region | AWS_REGION ;
            github-muehlbachler-mail-services-infrastructure/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-muehlbachler-mail-services-infrastructure/data/tailscale oauth_client_id | TS_OAUTH_CLIENT_ID ;
            github-muehlbachler-mail-services-infrastructure/data/tailscale oauth_secret | TS_OAUTH_SECRET ;
            github-muehlbachler-mail-services-infrastructure/data/hetzner token | HCLOUD_TOKEN

      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198 # v1.0.0
        with:
          organization: muhlba91
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:muhlba91

      - uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
        with:
          oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952 # v6.0.0
        with:
          command: preview
          stack-name: prod
          refresh: true
        env:
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"

  deploy:
    runs-on: ubuntu-latest
    name: Pulumi Deploy
    needs:
      - preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-muehlbachler-mail-services-infrastructure/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-muehlbachler-mail-services-infrastructure/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-muehlbachler-mail-services-infrastructure/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT ;
            github-muehlbachler-mail-services-infrastructure/data/aws region | AWS_REGION ;
            github-muehlbachler-mail-services-infrastructure/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-muehlbachler-mail-services-infrastructure/data/tailscale oauth_client_id | TS_OAUTH_CLIENT_ID ;
            github-muehlbachler-mail-services-infrastructure/data/tailscale oauth_secret | TS_OAUTH_SECRET ;
            github-muehlbachler-mail-services-infrastructure/data/hetzner token | HCLOUD_TOKEN

      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198 # v1.0.0
        with:
          organization: muhlba91
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:muhlba91

      - uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
        with:
          oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952 # v6.0.0
        with:
          command: up
          stack-name: prod
        env:
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"
